version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # แก้ให้ถูกต้อง
    
    ports:
      - "8080:8080"
    
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=Pawn Shop Management
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    
    extra_hosts:
      - "host.docker.internal:host-gateway"  # เพื่อเข้าถึง Backend localhost:3000
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3