version: '3.8'

services:
  pawn-ai-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    container_name: pawn-ai-chat-app
    
  # Uncomment if you need a reverse proxy like nginx
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl  # SSL certificates folder
  #   depends_on:
  #     - pawn-ai-chat
  #   restart: unless-stopped
