import { LoginRow, ExportRow, ViewRow, ChatRow, Tab } from "@/types/log-types";

const overview = [
  { label: "Logs ทั้งหมด", value: 28947 },
  { label: "Logs ในเดือนนี้", value: 3842 },
  { label: "จำนวนผู้ใช้งาน", value: 247 },
];

const tabs: { key: Tab; label: string; count: number }[] = [
  { key: "login", label: "ผู้ใช้/เข้าสู่ระบบ", count: 1847 },
  { key: "export", label: "ส่งออกไฟล์", count: 492 },
  { key: "view", label: "การเข้าถึงเมนู", count: 8623 },
  { key: "chat", label: "ประวัติแชท", count: 2156 },
];

const loginData: LoginRow[] = [
  {
    name: "ธวัชชัย ญาณศิริ",
    email: "thawatchai.y@pawnshop.go.th",
    datetime: "2025-07-24 14:32:15",
    action: "log_in",
    ip: "203.150.3.45",
    agent: "Chrome 127.0.0.0 บน Windows 11",
    session: "sess_tws_240724_1432",
    location: "กรุงเทพมหานคร, ประเทศไทย",
  },
  {
    name: "สุภาพร เจริญศักดิ์",
    email: "supaporn.j@pawnshop.go.th",
    datetime: "2025-07-24 14:28:42",
    action: "log_out",
    ip: "203.150.3.67",
    agent: "Edge 126.0.2592.68 บน Windows 10",
    session: "sess_spj_240724_1415",
    location: "เชียงใหม่, ประเทศไทย",
  },
  {
    name: "อนุชา พิทักษ์วงศ์",
    email: "anucha.p@pawnshop.go.th",
    datetime: "2025-07-24 14:25:18",
    action: "log_in",
    ip: "203.150.3.89",
    agent: "Firefox 128.0 บน macOS Sonoma",
    session: "sess_acp_240724_1425",
    location: "นครราชสีมา, ประเทศไทย",
  },
  {
    name: "วิภาวี สุขสวัสดิ์",
    email: "vipavee.s@pawnshop.go.th",
    datetime: "2025-07-24 14:20:07",
    action: "log_in",
    ip: "203.150.3.12",
    agent: "Chrome 127.0.0.0 บน Android 14",
    session: "sess_vps_240724_1420",
    location: "ขอนแก่น, ประเทศไทย",
  },
  {
    name: "ประดิษฐ์ ทองคำ",
    email: "pradit.t@pawnshop.go.th",
    datetime: "2025-07-24 14:15:33",
    action: "log_out",
    ip: "203.150.3.156",
    agent: "Safari 17.5 บน iOS 17.5.1",
    session: "sess_pdt_240724_1330",
    location: "ภูเก็ต, ประเทศไทย",
  },
  {
    name: "กัลยา มาลัยทอง",
    email: "kanaya.m@pawnshop.go.th",
    datetime: "2025-07-24 14:12:21",
    action: "log_in",
    ip: "203.150.3.78",
    agent: "Chrome 127.0.0.0 บน Windows 11",
    session: "sess_kym_240724_1412",
    location: "สงขลา, ประเทศไทย",
  },
  {
    name: "วิรัช ศรีสวัสดิ์",
    email: "virat.s@pawnshop.go.th",
    datetime: "2025-07-24 14:08:45",
    action: "log_in",
    ip: "203.150.3.234",
    agent: "Edge 126.0.2592.68 บน Windows 10",
    session: "sess_vrs_240724_1408",
    location: "อุดรธานี, ประเทศไทย",
  },
  {
    name: "นิตยา พงษ์พิพัฒน์",
    email: "nitaya.p@pawnshop.go.th",
    datetime: "2025-07-24 14:05:16",
    action: "log_out",
    ip: "203.150.3.91",
    agent: "Chrome 127.0.0.0 บน Windows 11",
    session: "sess_nyp_240724_1345",
    location: "นครศรีธรรมราช, ประเทศไทย",
  },
  {
    name: "สมชาย รัตนวิไล",
    email: "somchai.r@pawnshop.go.th",
    datetime: "2025-07-24 14:02:58",
    action: "log_in",
    ip: "203.150.3.145",
    agent: "Firefox 128.0 บน Ubuntu 22.04",
    session: "sess_scr_240724_1402",
    location: "ระยอง, ประเทศไทย",
  },
  {
    name: "พิมพ์ชนก แสงอรุณ",
    email: "pimchanok.s@pawnshop.go.th",
    datetime: "2025-07-24 13:58:12",
    action: "log_in",
    ip: "203.150.3.203",
    agent: "Chrome 127.0.0.0 บน Windows 10",
    session: "sess_pcs_240724_1358",
    location: "อุบลราชธานี, ประเทศไทย",
  },
];

const exportData: ExportRow[] = [
  {
    name: "ธวัชชัย ญาณศิริ",
    email: "thawatchai.y@pawnshop.go.th",
    type: "รายงานรับจำนำประจำเดือน",
    format: "CSV",
    records: 2847,
    size: "1.2 MB",
    status: "success",
    datetime: "2025-07-24 13:45:23",
  },
  {
    name: "สุภาพร เจริญศักดิ์",
    email: "supaporn.j@pawnshop.go.th",
    type: "รายงานขายทอดตลาด",
    format: "CSV",
    records: 1546,
    size: "892 KB",
    status: "success",
    datetime: "2025-07-24 12:30:15",
  },
  {
    name: "อนุชา พิทักษ์วงศ์",
    email: "anucha.p@pawnshop.go.th",
    type: "รายงานผู้ใช้งานระบบ",
    format: "CSV",
    records: 247,
    size: "156 KB",
    status: "success",
    datetime: "2025-07-24 11:22:41",
  },
  {
    name: "วิภาวี สุขสวัสดิ์",
    email: "vipavee.s@pawnshop.go.th",
    type: "รายงานสินค้าคงคลัง",
    format: "CSV",
    records: 5934,
    size: "2.8 MB",
    status: "processing",
    datetime: "2025-07-24 10:15:32",
  },
  {
    name: "ประดิษฐ์ ทองคำ",
    email: "pradit.t@pawnshop.go.th",
    type: "รายงานการเงินรายวัน",
    format: "CSV",
    records: 1203,
    size: "734 KB",
    status: "success",
    datetime: "2025-07-24 09:45:18",
  },
  {
    name: "กัลยา มาลัยทอง",
    email: "kanaya.m@pawnshop.go.th",
    type: "รายงานลูกค้าใหม่",
    format: "CSV",
    records: 438,
    size: "267 KB",
    status: "failed",
    datetime: "2025-07-24 09:12:07",
  },
  {
    name: "วิรัช ศรีสวัสดิ์",
    email: "virat.s@pawnshop.go.th",
    type: "รายงานดอกเบี้ยค้างชำระ",
    format: "CSV",
    records: 892,
    size: "445 KB",
    status: "success",
    datetime: "2025-07-24 08:55:49",
  },
  {
    name: "นิตยา พงษ์พิพัฒน์",
    email: "nitaya.p@pawnshop.go.th",
    type: "รายงานสาขาทั้งหมด",
    format: "CSV",
    records: 3765,
    size: "1.9 MB",
    status: "success",
    datetime: "2025-07-24 08:33:21",
  },
];

const viewData: ViewRow[] = [
  {
    name: "ธวัชชัย ญาณศิริ",
    email: "thawatchai.y@pawnshop.go.th",
    menuId: "menu_pawn_data",
    menuName: "ข้อมูลตัวรับจำนำ",
  },
  {
    name: "สุภาพร เจริญศักดิ์",
    email: "supaporn.j@pawnshop.go.th",
    menuId: "menu_asset_types",
    menuName: "ประเภททรัพย์และราคา",
  },
  {
    name: "อนุชา พิทักษ์วงศ์",
    email: "anucha.p@pawnshop.go.th",
    menuId: "menu_user",
    menuName: "จัดการข้อมูลผู้ใช้",
  },
  {
    name: "วิภาวี สุขสวัสดิ์",
    email: "vipavee.s@pawnshop.go.th",
    menuId: "menu_reports",
    menuName: "รายงานและสถิติ",
  },
  {
    name: "ประดิษฐ์ ทองคำ",
    email: "pradit.t@pawnshop.go.th",
    menuId: "menu_logs",
    menuName: "ประวัติการใช้งาน",
  },
  {
    name: "กัลยา มาลัยทอง",
    email: "kanaya.m@pawnshop.go.th",
    menuId: "menu_dashboard",
    menuName: "ข้อมูลตั๋วรับจำนำ",
  },
  {
    name: "วิรัช ศรีสวัสดิ์",
    email: "virat.s@pawnshop.go.th",
    menuId: "menu_asset_types",
    menuName: "ประเภททรัพย์และราคา",
  },
  {
    name: "นิตยา พงษ์พิพัฒน์",
    email: "nitaya.p@pawnshop.go.th",
    menuId: "menu_customers",
    menuName: "ข้อมูลลูกค้า",
  },
  {
    name: "สมชาย รัตนวิไล",
    email: "somchai.r@pawnshop.go.th",
    menuId: "menu_transactions",
    menuName: "ประวัติการทำธุรกรรม",
  },
  {
    name: "พิมพ์ชนก แสงอรุณ",
    email: "pimchanok.s@pawnshop.go.th",
    menuId: "menu_user",
    menuName: "จัดการข้อมูลผู้ใช้",
  },
];

const chatData: ChatRow[] = [
  {
    name: "ธวัชชัย ญาณศิริ",
    email: "thawatchai.y@pawnshop.go.th",
    topic: "สอบถามเกี่ยวกับการรับจำนำทองคำ",
    datetime: "2025-07-24 14:25:32",
    messageId: "chat_tws_240724_001",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "สวัสดีครับ ผมอยากสอบถามเกี่ยวกับการรับจำนำทองคำครับ",
        time: "14:25:32",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณธวัชชัย ยินดีให้ข้อมูลเรื่องการรับจำนำทองคำครับ ขณะนี้เรารับจำนำทองคำ 96.5% ในราคา 32,500 บาทต่อบาท และทอง 90% ในราคา 30,800 บาทต่อบาท มีอะไรเพิ่มเติมที่อยากทราบไหมครับ?",
        time: "14:25:45",
      },
      {
        from: "user",
        text: "อัตราดอกเบี้ยเป็นอย่างไรครับ",
        time: "14:26:02",
      },
      {
        from: "ai",
        text: "อัตราดอกเบี้ยสำหรับการรับจำนำทองคำอยู่ที่ 1.25% ต่อเดือน โดยสามารถไถ่คืนได้ภายใน 6 เดือน หากเกินกำหนดจะมีการประมูลขายทอดตลาดครับ",
        time: "14:26:15",
      },
      {
        from: "user",
        text: "ขอบคุณครับ ข้อมูลครบแล้ว",
        time: "14:26:28",
      },
    ],
  },
  {
    name: "สุภาพร เจริญศักดิ์",
    email: "supaporn.j@pawnshop.go.th",
    topic: "สอบถามการประมูลขายทอดตลาด",
    datetime: "2025-07-24 13:42:18",
    messageId: "chat_spj_240724_002",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "ดีค่ะ อยากทราบเกี่ยวกับการประมูลขายทอดตลาดค่ะ",
        time: "13:42:18",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณสุภาพร การประมูลขายทอดตลาดจะจัดขึ้นทุกวันพุธและเสาร์ เวลา 10:00 น. ที่สำนักงานใหญ่ครับ สามารถดูรายการสินค้าได้ล่วงหน้า 3 วัน",
        time: "13:42:30",
      },
      {
        from: "user",
        text: "มีค่าธรรมเนียมในการเข้าร่วมประมูลไหมคะ",
        time: "13:42:45",
      },
      {
        from: "ai",
        text: "ไม่มีค่าธรรมเนียมในการเข้าร่วมประมูลครับ แต่หากชนะการประมูลต้องชำระเงินเต็มจำนวนในวันเดียวกัน และมีค่าธรรมเนียมการโอน 1% ของราคาประมูล",
        time: "13:42:58",
      },
    ],
  },
  {
    name: "อนุชา พิทักษ์วงศ์",
    email: "anucha.p@pawnshop.go.th",
    topic: "สอบถามการรับจำนำเครื่องใช้ไฟฟ้า",
    datetime: "2025-07-24 12:15:47",
    messageId: "chat_acp_240724_003",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "ครับ อยากสอบถามว่าเรารับจำนำเครื่องใช้ไฟฟ้าอะไรบ้างครับ",
        time: "12:15:47",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณอนุชา เรารับจำนำเครื่องใช้ไฟฟ้าหลายประเภท เช่น โทรศัพท์มือถือ แท็บเล็ต โน๊ตบุ๊ค กล้องดิจิทัล เครื่องเสียง แต่ต้องเป็นของแท้และใช้งานได้ปกติครับ",
        time: "12:16:02",
      },
      {
        from: "user",
        text: "แล้วเกณฑ์การประเมินราคาเป็นอย่างไรครับ",
        time: "12:16:20",
      },
      {
        from: "ai",
        text: "เกณฑ์การประเมินจะดูจากสภาพของสินค้า อายุการใช้งาน ราคาตลาดปัจจุบัน และความต้องการในตลาด โดยทั่วไปจะได้ประมาณ 40-60% ของราคาตลาดครับ",
        time: "12:16:35",
      },
    ],
  },
  {
    name: "วิภาวี สุขสวัสดิ์",
    email: "vipavee.s@pawnshop.go.th",
    topic: "สอบถามการต่ออายุสัญญาจำนำ",
    datetime: "2025-07-24 11:33:21",
    messageId: "chat_vps_240724_004",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "สวัสดีค่ะ อยากสอบถามเรื่องการต่ออายุสัญญาจำนำค่ะ",
        time: "11:33:21",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณวิภาวี สำหรับการต่ออายุสัญญาจำนำ สามารถทำได้ก่อนครบกำหนด 7 วัน โดยชำระดอกเบี้ยที่ค้างอยู่ แล้วจะได้อายุใหม่อีก 6 เดือนครับ",
        time: "11:33:35",
      },
      {
        from: "user",
        text: "ถ้าไม่สามารถมาต่อด้วยตัวเองได้ ให้คนอื่นมาแทนได้ไหมคะ",
        time: "11:33:52",
      },
      {
        from: "ai",
        text: "ได้ครับ แต่ต้องมีหนังสือมอบอำนาจที่ถูกต้องตามกฎหมาย พร้อมสำเนาบัตรประชาชนของผู้มอบและผู้รับมอบอำนาจ และต้องนำต้นฉบับตั๋วจำนำมาด้วยครับ",
        time: "11:34:08",
      },
    ],
  },
  {
    name: "ประดิษฐ์ ทองคำ",
    email: "pradit.t@pawnshop.go.th",
    topic: "สอบถามการรับจำนำรถยนต์",
    datetime: "2025-07-24 10:28:15",
    messageId: "chat_pdt_240724_005",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "ครับ อยากทราบเรื่องการรับจำนำรถยนต์ครับ",
        time: "10:28:15",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณประดิษฐ์ เรารับจำนำรถยนต์ป้ายแดงที่มีอายุไม่เกิน 15 ปี โดยประเมินจากสภาพรถ อายุ และราคาตลาด วงเงินสูงสุด 2 ล้านบาทครับ",
        time: "10:28:30",
      },
      {
        from: "user",
        text: "เอกสารที่ต้องใช้มีอะไรบ้างครับ",
        time: "10:28:45",
      },
      {
        from: "ai",
        text: "เอกสารที่ต้องใช้ ได้แก่ เล่มทะเบียนรถ ใบอนุญาตขับขี่ บัตรประชาชน ทะเบียนบ้าน และหนังสือยินยอมจากคู่สมรส (ถ้ามี) รถต้องไม่มีภาระผูกพันครับ",
        time: "10:29:02",
      },
    ],
  },
  {
    name: "กัลยา มาลัยทอง",
    email: "kanaya.m@pawnshop.go.th",
    topic: "สอบถามการเปิดบัญชีลูกค้าใหม่",
    datetime: "2025-07-24 09:45:33",
    messageId: "chat_kym_240724_006",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "สวัสดีค่ะ อยากทราบขั้นตอนการเปิดบัญชีลูกค้าใหม่ค่ะ",
        time: "09:45:33",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณกัลยา การเปิดบัญชีลูกค้าใหม่ใช้เวลาประมาณ 15 นาที ต้องนำบัตรประชาชน ทะเบียนบ้าน และหนังสือรับรองเงินเดือน (ถ้ามี) มาให้เจ้าหน้าที่ตรวจสอบครับ",
        time: "09:45:48",
      },
      {
        from: "user",
        text: "มีค่าธรรมเนียมในการเปิดบัญชีไหมคะ",
        time: "09:46:05",
      },
      {
        from: "ai",
        text: "ไม่มีค่าธรรมเนียมในการเปิดบัญชีครับ เป็นบริการฟรี แต่หากทำธุรกรรมจำนำจะมีค่าธรรมเนียมการทำสัญญาตามอัตราที่กำหนดครับ",
        time: "09:46:18",
      },
    ],
  },
  {
    name: "วิรัช ศรีสวัสดิ์",
    email: "virat.s@pawnshop.go.th",
    topic: "สอบถามระบบการชำระดอกเบี้ย",
    datetime: "2025-07-24 08:52:47",
    messageId: "chat_vrs_240724_007",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "ครับ อยากทราบเกี่ยวกับระบบการชำระดอกเบี้ยครับ",
        time: "08:52:47",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณวิรัช สำหรับการชำระดอกเบี้ย สามารถชำระได้หลายช่องทาง เช่น ที่เคาน์เตอร์ ตู้ ATM โมบายแบงก์กิ้ง หรือแอปพลิเคชันของเราครับ",
        time: "08:53:02",
      },
      {
        from: "user",
        text: "ถ้าชำระล่าช้าจะมีค่าปรับไหมครับ",
        time: "08:53:18",
      },
      {
        from: "ai",
        text: "หากชำระล่าช้าจะมีค่าปรับ 2% ต่อเดือน นับจากวันที่ครบกำหนดชำระ แต่หากล่าช้าเกิน 30 วัน อาจส่งผลต่อการพิจารณาสินเชื่อครั้งต่อไปครับ",
        time: "08:53:35",
      },
    ],
  },
  {
    name: "นิตยา พงษ์พิพัฒน์",
    email: "nitaya.p@pawnshop.go.th",
    topic: "สอบถามการรับจำนำเครื่องประดับ",
    datetime: "2025-07-24 08:15:29",
    messageId: "chat_nyp_240724_008",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "สวัสดีค่ะ อยากสอบถามการรับจำนำเครื่องประดับค่ะ",
        time: "08:15:29",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณนิตยา เรารับจำนำเครื่องประดับทองคำ เพชร แพลทินัม และอัญมณีต่างๆ โดยจะประเมินจากน้ำหนัก ความบริสุทธิ์ และคุณภาพของเครื่องประดับครับ",
        time: "08:15:44",
      },
      {
        from: "user",
        text: "เครื่องประดับที่มีตัวหนังสือจำนำได้ไหมคะ",
        time: "08:16:02",
      },
      {
        from: "ai",
        text: "ได้ครับ แต่อาจส่งผลต่อราคาประเมิน เนื่องจากตัวหนังสือจะลดความสวยงามและมูลค่าในการขายต่อ แต่ยังคงประเมินจากน้ำหนักทองคำหรือเพชรตามปกติครับ",
        time: "08:16:18",
      },
    ],
  },
  {
    name: "สมชาย รัตนวิไล",
    email: "somchai.r@pawnshop.go.th",
    topic: "สอบถามการรับจำนำที่ดิน",
    datetime: "2025-07-24 07:43:16",
    messageId: "chat_scr_240724_009",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "ครับ อยากทราบเรื่องการรับจำนำที่ดินครับ",
        time: "07:43:16",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณสมชาย เรารับจำนำที่ดินที่มีโฉนดที่ดินหรือน.ส.3ก ในพื้นที่ที่เหมาะสม วงเงินขึ้นอยู่กับราคาประเมินของธนาคารแห่งประเทศไทยครับ",
        time: "07:43:32",
      },
      {
        from: "user",
        text: "ระยะเวลาการจำนำเป็นอย่างไรครับ",
        time: "07:43:48",
      },
      {
        from: "ai",
        text: "สำหรับการจำนำที่ดิน ระยะเวลาสูงสุด 3 ปี อัตราดอกเบี้ย 8% ต่อปี สามารถต่ออายุได้ แต่ต้องผ่านการประเมินราคาใหม่ทุกครั้งครับ",
        time: "07:44:05",
      },
    ],
  },
  {
    name: "พิมพ์ชนก แสงอรุณ",
    email: "pimchanok.s@pawnshop.go.th",
    topic: "สอบถามการรับจำนำมอเตอร์ไซค์",
    datetime: "2025-07-24 07:12:38",
    messageId: "chat_pcs_240724_010",
    action: "ดูรายละเอียดเพิ่มเติม",
    transcript: [
      {
        from: "user",
        text: "สวัสดีค่ะ อยากสอบถามการรับจำนำมอเตอร์ไซค์ค่ะ",
        time: "07:12:38",
      },
      {
        from: "ai",
        text: "สวัสดีครับคุณพิมพ์ชนก เรารับจำนำมอเตอร์ไซค์ป้ายแดงที่มีอายุไม่เกิน 10 ปี ประเมินจากสภาพและราคาตลาด วงเงินสูงสุด 150,000 บาทครับ",
        time: "07:12:53",
      },
      {
        from: "user",
        text: "ต้องมีเอกสารอะไรบ้างคะ",
        time: "07:13:08",
      },
      {
        from: "ai",
        text: "เอกสารที่ต้องใช้ ได้แก่ เล่มทะเบียนรถ ใบอนุญาตขับขี่ บัตรประชาชน ทะเบียนบ้าน และรถต้องไม่มีภาระผูกพัน พร้อมกุญแจสำรองครับ",
        time: "07:13:25",
      },
    ],
  },
];
